alias cep38-build='docker build --no-cache -t cep-38 .'
alias cep38-pull='docker pull mmuzaf/cep-38 && docker tag mmuzaf/cep-38 cep-38'
alias cep38-run='docker run -it --rm --cap-add NET_ADMIN cep-38'
alias cep38-bash='docker exec -it $(docker ps -ql --filter status=running --filter ancestor=cep-38) bash'
alias cep38-stop='docker stop $(docker ps -q --filter ancestor=cep-38)'
alias cep38-remove='docker rmi cep-38'
